import type { Inventory, OutputRenderer, Project } from "../types.ts";

/**
 * Render inventory as a markdown CV.
 */
export class MarkdownRenderer implements OutputRenderer {
  name = "markdown";

  render(inventory: Inventory, selectedIds: string[]): string {
    const selected = inventory.projects.filter(
      (p) => selectedIds.includes(p.id) && !p.tags.includes("removed")
    );

    if (selected.length === 0) {
      return "# Technical CV\n\n*No projects selected.*\n";
    }

    const lines: string[] = [
      "# Technical CV",
      "",
      `*Generated by llm-cv on ${new Date().toISOString().split("T")[0]}*`,
      "",
      "---",
      "",
    ];

    for (const project of selected) {
      lines.push(...renderProject(project));
      lines.push("");
    }

    // Summary footer
    const languages = countBy(selected, (p) => p.language);
    const dateRange = getOverallDateRange(selected);

    lines.push("---", "");
    lines.push(`**${selected.length} projects** across ${Object.keys(languages).length} languages`);
    if (dateRange) {
      lines.push(`| ${dateRange.start} to ${dateRange.end}`);
    }
    lines.push("");

    return lines.join("\n");
  }
}

function renderProject(project: Project): string[] {
  const lines: string[] = [];
  const name = project.suggestedName || project.displayName;
  const dateStr = formatDateRange(project.dateRange);

  lines.push(`## ${name}${dateStr ? ` (${dateStr})` : ""}`);
  lines.push("");

  // Tech stack
  const tech = project.analysis?.techStack ?? [project.language];
  if (tech.length > 0) {
    lines.push(`**Tech:** ${tech.join(", ")}`);
    lines.push("");
  }

  // Summary
  if (project.analysis?.summary) {
    lines.push(project.analysis.summary);
    lines.push("");
  }

  // Contributions
  if (project.analysis?.contributions && project.analysis.contributions.length > 0) {
    lines.push("**Key contributions:**");
    for (const c of project.analysis.contributions) {
      lines.push(`- ${c}`);
    }
    lines.push("");
  }

  // Metadata line
  const meta: string[] = [];
  if (project.commitCount > 0) {
    meta.push(`${project.commitCount} commits`);
  }
  if (project.authorCommitCount > 0 && project.authorCommitCount !== project.commitCount) {
    meta.push(`${project.authorCommitCount} by me`);
  }
  if (project.frameworks.length > 0) {
    meta.push(project.frameworks.join(", "));
  }
  if (meta.length > 0) {
    lines.push(`*${meta.join(" | ")}*`);
    lines.push("");
  }

  return lines;
}

function formatDateRange(range: { start: string; end: string; approximate: boolean }): string {
  if (!range.start && !range.end) return "";
  const prefix = range.approximate ? "~" : "";
  const start = formatMonth(range.start);
  const end = formatMonth(range.end);
  if (start === end) return `${prefix}${start}`;
  return `${prefix}${start} — ${end}`;
}

function formatMonth(dateStr: string): string {
  if (!dateStr) return "?";
  const [year, month] = dateStr.split("-");
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const monthName = months[parseInt(month || "0", 10) - 1] || month;
  return `${monthName} ${year}`;
}

function countBy<T>(items: T[], key: (item: T) => string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const item of items) {
    const k = key(item);
    counts[k] = (counts[k] || 0) + 1;
  }
  return counts;
}

function getOverallDateRange(projects: Project[]): { start: string; end: string } | null {
  const starts = projects.map((p) => p.dateRange.start).filter(Boolean).sort();
  const ends = projects.map((p) => p.dateRange.end).filter(Boolean).sort();
  if (starts.length === 0) return null;
  return {
    start: starts[0]!,
    end: ends[ends.length - 1] || starts[0]!,
  };
}
